version: '3.9'
services:

  postgres:
    extends:
      file: ./services.yml
      service: postgres
    environment:
      POSTGRES_PASSWORD: password

  redis:
    extends:
      file: ./services.yml
      service: redis
    
  dev:
    tty: true
    build:
      context: ..
      dockerfile: .docker/dev/Dockerfile
    restart: unless-stopped
    volumes:
      - ..:/data/repo
      - ../.vscode/.pnpm:/code/.vscode/.pnpm

