version: '3.9'
services:

  postgres:
    image: postgres
    restart: always
    volumes:
     - ./data/postgres/db:/data/db

  redis:
    image: redis
    restart: always
    volumes:
     - ./data/redis:/data